version: "3.4"

services:
  node:
    container_name: node
    user: "${UID}:${GID}"
    build:
      context: ./node
    ports:
      - "3000:3000"
      - "3001:3001"
    volumes:
      - ./node/app:/home/node/app

  # ganache:
  #   container_name: ganache
  #   build:
  #     context: ./ganache
  #   devices:
  #     - /dev/fuse:/dev/fuse
  #   volumes:
  #     - /tmp/.X11-unix:/tmp/.X11-unix
  #   ports:
  #     - "7545:7545"
  #   cap_add:
  #     - SYS_ADMIN
  #   environment:
  #     - DISPLAY

  bootnode:
    container_name: bootnode
    user: "${UID}:${GID}"
    build:
      context: ./bootnode

  private-chain-1:
    container_name: private-chain-1
    user: "${UID}:${GID}"
    build:
      context: ./private-chain
    ports:
      - "8545:8545"
    environment:
      - account=ddffffc540bc00e915bef356aad1be85ccac1b4c
      - miner_threads=1

  private-chain-2:
    container_name: private-chain-2
    user: "${UID}:${GID}"
    build:
      context: ./private-chain
    environment:
      - account=ddffffc540bc00e915bef356aad1be85ccac1b4c
      - miner_threads=2
